### ISSUE TITLE
Login redirect from paths other than /ceda are incorrect

### ISSUE THREAD

**Issue by watucker** [cedadev/archive_browser#115]
If you go to a data centre path other than /ceda, e.g. https://data.ceda.ac.uk/bodc/, the redirect from the login path is:

/account/signin/?r=http%3A%2F%2F127.0.0.1%3A8000%2F

This will redirect to localhost, which is not helpful.

**Comment by watucker** [comment]
Hi @dwest77a , this is an error that a user noticed earlier, would be good to get it fixed though it's not really causing any problems right now.

**Comment by dwest77a** [comment]
I have in dctheme_update a setting that disables the login/sign in option as I thought that was the plan? I can still look into this in case we need the login later?

**Comment by dwest77a** [comment]
The redirect url comes from request.build_absolute_uri() which for the live version at data.ceda.ac.uk I can't see why it would default to 127.0.0.1:8000.

**Comment by dwest77a** [comment]
No longer using login services for archive_browser so this is no longer an issue
