### ISSUE TITLE
Update on MOLES changes

### ISSUE THREAD

**Issue by rsmith013** [cedadev/archive_browser#14]
1. Update title - Observation | Observation Collection
 - trigger: title is changed
 - initiates : update_title(url, title)
- Update by query using url

2. Update path - Observation
- trigger: path is changed 
- initiates: update_path (url, path, title)

- update by query on record url to MOLES collection or blank
- use new dataset path to update by query with MOLES information

3. Release Dataset - Observation
 - trigger: publication state changes from working to one of [preview, published]
 - initiates: update_dataset(url, path, title)

- update by query below path

4. Release Collection - Observation Collection
 - trigger: publication state changes from working to one of [preview, published]
 - initiates: update_collection(lilst_of_paths)
 - publication state changes from working to one of [preview, published]
- Go up from top of datasets as far as there is a unique collection
- Update by query that path any record which is not already a dataset

5. Delete - Observation |Observation Collection
 - trigger: record is deleted
 - initiates: delete_catalogue_record(url)

- Remove MOLES meta from all records matching URL

**Comment by spepler** [comment]
In reindex version a strategy of not caching the moles record in the index is used this makes the moles content dynamic.
