### ISSUE TITLE
Logout is broken

### ISSUE THREAD

**Issue by philipkershaw** [cedadev/archive_browser#33]
When I try the log out button it doesn't work.  Status shows me still signed in and the session cookie is still there.

**Comment by philipkershaw** [comment]
Using Chrome Version 73.0.3683.103

**Comment by gap736uk** [comment]
likewise if you have logged in elsewhere (e.g. catalogue) it doesn't refresh to show you are now logged in. (Chrome)

**Comment by spepler** [comment]
Probably still broken?

**Comment by spepler** [comment]
@watucker Is this still true?

**Comment by gap736uk** [comment]
Looks like it is still broken to me.

**Comment by watucker** [comment]
Yeah.. it's a weird cookie thing. Every time I try to figure out why I waste hours, so I learned to pretend this issue doesn't exist.

**Comment by watucker** [comment]
It wont be a problem with the new login system though, so perhaps not worth looking at at this point.

**Comment by spepler** [comment]
Sounds like a won't fix.
