### ISSUE TITLE
Symlink files are being represented as directories

### ISSUE THREAD

**Issue by rsmith013** [cedadev/archive_browser#55]
example: /badc/cmip6/data/CMIP6/CMIP/CCCma/CanESM5/abrupt-4xCO2/r1i1p1f1/day/rlut/gn/v20190429/rlut_day_CanESM5_abrupt-4xCO2_r1i1p1f1_gn_18500101-20001231.nc

**Comment by spepler** [comment]
solved in the reindexed version
