### ISSUE TITLE
Display projects in interface

### ISSUE THREAD

**Issue by rsmith013** [cedadev/archive_browser#56]
Though it looks like the ‘project’ objects that get returned aren’t being used in the data.ceda.ac.uk interface atm… e.g. see : data.ceda.ac.uk/badc/cmip5/data/cmip5/output2/MOHC/
cf:
https://catalogue.ceda.ac.uk/api/v0/obs/get_info/badc/cmip5/data/cmip5/output2/MOHC/

**Comment by spepler** [comment]
Don't do this.
