### ISSUE TITLE
Readme descriptions displayed even though there is a MOLES link

### ISSUE THREAD

**Issue by rsmith013** [cedadev/archive_browser#66]
http://data.ceda.ac.uk/badc/chilbolton/data/disdrometer_chilbolton/2003

**Comment by rsmith013** [comment]
@gap736uk How often are the readmes below a MOLES record descriptive. In this case, they clearly are not but might it be useful in other situations to show the readme first line below a MOLES record?

**Comment by rsmith013** [comment]
The change is minimal but want to check quickly with @gap736uk

**Comment by gap736uk** [comment]
Comments below as my train of thought as I type....

I was wondering about this myself... there are LOTS of reame files that will be in the archive which are quire historic in nature... and some which won't relate to a 'cataloging' perspective per se... I did a _quick_ Kibana check and looks like there are _way_ more than we could possibly look at reviewing.

However, I think taking the approach that we're looking to provide signposts to users as to what are the directory contents then there are two ways to view this...

1) Just expose them where they crop up and there isn't a MOLES record for that level... _may_ give a hint to the directory contents but that's assuming that the first line (which is the only one you take) gives something meaningful within the set character limit for the data.ceda display
2) ignore them when within a directory covered by a parent directory with a MOLES Obs record (note, Obs, not Obs Col!) 

2 - prevents us from giving useful signposting below a dataset's top directory but does makes it clearer for users.

Do you use any particular check to see if it s a 'ceda' 00README file (IIRC they used to have the pattern of :

<meaningful title string>
==================

unlike other readmes

could that be used to know which ones to use and which to ignore the content of?

**Comment by rsmith013** [comment]
@gap736uk At the moment there is no check on the readme. Just gets the top line from a 00README file.

This is probably one of those things where it is difficult to come up with a  rule which will work in all cases so better just to leave the readmes display and then they can be used to give more specific signposting. It's probably more an issue with the readme content than the display mechanism.
