### ISSUE TITLE
new data.ceda service missing 'readme' content for directories where no MOLES look up is possible.

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#75]
Old system pulled back content from 00READMEs when there wasn't a MOLES look-up possible.

This would cover the following use cases:
1. top level directory labelling (now only PDC has a label as we added in a record to cover that top level only)
2. the MOLES look -up could not resolve to one record to return for that directory [.e.g. there would be multiple Collection level records returned, or not MOLES coverage]

**Comment by spepler** [comment]
Deliberately left out for the moment, but we could add it back in.

**Comment by spepler** [comment]
Does this but needs to reindex 00README to make it show up.
