### ISSUE TITLE
new data.ceda.ac.uk service is slow

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#76]
each directory load is much slower than the present system  - this will be because it will be doing the MOLES API look-up on the fly.

**Comment by spepler** [comment]
There is a caching system it is only slow the first time. There is some tuning to do.

**Comment by spepler** [comment]
I could write a better caching algorithm.  Needs to time limit, Needs last retrieved value and needs a wat to force an individual value to update.

**Comment by spepler** [comment]
Now got a proper complicated caching algorithm.  I think it will be ok. deployed on the staging service
