### ISSUE TITLE
new data.ceda. - listing parameter info makes list of files unusable

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#78]
Don't show list of parameters in default view.. needs toggle view to show them or list at top and 'filter on parameter' option

Otherwise you quickly lose the ability to scroll sensibly through the file list.

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/12462002/180735085-b8901862-95ea-4c73-ac58-2b3e27c7adbe.png">

**Comment by spepler** [comment]
Just removed it for the moment.
