### ISSUE TITLE
data.ceda.ac.uk - indicate how many datasets held in sub-dirs

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#79]
When dropping down the directory tree structure you are now listing number of files/total volume...

Just wondering if you could also list the number of datasets/collection for each sub-folder of the directory being looked at?

e.g. under 
https://archive-browser-main.130.246.130.221.nip.io/badc/CDs/step87

it's hard to know which path to do down to the actual datasets.

**Comment by spepler** [comment]
This is too hard to do.

**Comment by gap736uk** [comment]
could be done with MOLES API call....

e.g. 

http://api.catalogue.ceda.ac.uk/api/v2/observations/?result_field__dataPath__startswith=/badc/ukmo-midas/&fields=uuid

**Comment by spepler** [comment]
Anything can be done but I am not doing it pre-stac and that means not in this app.
