### ISSUE TITLE
00README files and .html - why not just view in browser?

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#80]
00README files lack the .txt ending so won't open automatically in browser... instead user needs to download the file then open it up in a text reader (which because it lacks the .txt suffix wont be automatically proffered by most OSs).

This makes it a painful process for people to look at these files.

Can we make these much more intuitive/immediately available for users to see the content of _in the browser_ so that they don't have to lose the context where the info is meant to aid their user of the archive?

Similarly.. .html files end up needing to be downloaded rather than being viewable in the browser which detracts from their usability:

<img width="977" alt="image" src="https://user-images.githubusercontent.com/12462002/180738859-05147d6d-06e4-49ab-a67d-8ffd082d6c35.png">

**Comment by spepler** [comment]
works not for html files. There is no way it can work for 00README files as the dap service does not know how to view them.
