### ISSUE TITLE
new data.ceda: why show folder size as 0 bytes?

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#81]
Why clutter the view with showing folders are of zero length? 

Perhaps either not show this for folders/symlinks. OR show total volumes of content below those paths ?

<img width="977" alt="image" src="https://user-images.githubusercontent.com/12462002/180738293-cc264655-43c9-4d35-9205-dc14d4ecb0d4.png">

**Comment by spepler** [comment]
Removed unless its a file.
