### ISSUE TITLE
new data.ceda: top level needs descriptors

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#82]
With the top level now representing EDS holdings, not just CEDA the sub-dirs need to be labelled properly. Some attempt to get around the old way of doing this was attempted, but only worked for PDC to date:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/12462002/180739238-1a9657c8-5d25-47de-be20-b6fcc268fa56.png">

We could add in dummy 'dataset' records for the different top level dirs, but this really isn't the proper way to do this as there would be other issues as a consequence... and those records aren't really designed for that purpose. Instead something 'proper' ought to be done where there are links an appropriate landing page for the associated top level directory.

**Comment by spepler** [comment]
Perhaps a reinstated readme way of doing it?

**Comment by gap736uk** [comment]
might want to understand what we want to show here first?

 - Simplest is to just have some plain text descriptor picked out of the READMEs... and then just add in the appropriate readme there.

 - would there be a need to have it as a link to something ? Or would that be too confusing at that point?
 
 Also, whilst we have the MOLES look-up for our paths, how would we support a similar function for non-CEDA content? It ought to be possible somehow....

**Comment by spepler** [comment]
Top level readmes now possible.
