### ISSUE TITLE
new data.ceda : directory contents listing 'button' length and position

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#83]
I spotted that the new 'button' listing contents sometimes drops down to the next line when the text length gets too long:

might be worth consisdering position or a better summary of number of files (e.g. instead of writing `131,663,523 files how about 131M files' ... only bother listing accurate number of files when :

1.  within the new window that lists the summary
2. when in a sub-folder actually listing files only (i.e. reached the end point)
3. when below 10,000 files perhaps?

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/12462002/180742255-458c7908-3056-46da-ae02-a3dc4601295e.png">

**Comment by spepler** [comment]
Not going to fix this.
