### ISSUE TITLE
Files that are on tape are shown as downloadable 

### ISSUE THREAD

**Issue by alisonwaterfall** [cedadev/archive_browser#84]
Files on tape seem to be shown as normal downloadable files (e.g. https://archive-browser-main.130.246.130.221.nip.io/neodc/esacci/cloud/data/version3/L2/ATSR2-AATSR/CLOUD/v3.0/AATSR_ENVISAT/2002/05/20)   that just show a 404 error if you try and download them.
In the current data.ceda, you get an information message to say they are on tape instead...

**Comment by spepler** [comment]
Now looks like the old version.
