### ISSUE TITLE
Use loading icon when still loading up summary box contents

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#88]
When going to a page and it is still obtaining/loading the links to MOLES records you are presented with the swirly-go-round icon until the MOLES record details load up.

Meanwhile, in the summary box (showing volume, number of files etc) you don't get such an indicator that content are still loading and it can present the user with incorrect information.... these details may eventually appear sometime later, but there's no indication that this is being obtained still ... 

Suggest adding in the swirly-go-round loading icon until the content load has completed.

Example of this can be seen in the latest MIDAS Open dataset versions..e.g. under https://data.ceda.ac.uk/badc/ukmo-midas-open/data/uk-soil-temperature-obs/dataset-version-202207.  the values only come up after a while (and also on page refresh?)

Whilst the content are loading the wording that is provided therefore also looks incomplete.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/12462002/188107543-b6eee5ae-d04e-4477-8414-528a572e618e.png">

**Comment by spepler** [comment]
done
