### ISSUE TITLE
Suggest alt content separator for archive summery content

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#89]
Present use of comma to separate content items and also used for separator for integers looks a little messy on the archive summary content.

suggest switching this to having semi-colon or pipe separator for the different field items

<img width="241" alt="image" src="https://user-images.githubusercontent.com/12462002/188107979-8bf3a4bf-cf10-4dd3-ada2-9d42d3b0fed9.png">

**Comment by spepler** [comment]
used pipe.
