### ISSUE TITLE
don't show download link for symlinked folders

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#91]
The download link (on far right) doesn't make sense for symlinked folders. E.g. see (this also threw up a 403 error page): 

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/12462002/188117956-385defe5-dad5-473d-a9a2-a05a00535462.png">

**Comment by spepler** [comment]
I think I should just remove download for any link.

**Comment by spepler** [comment]
fixed.
