### ISSUE TITLE
improve error pages

### ISSUE THREAD

**Issue by gap736uk** [cedadev/archive_browser#92]
403 error page presentation is a bad end-point to display the user as it presents them with a non-branded page with no signpost for the user about their next steps to resolve the issue they have encountered.

Consider all such error pages and provide a more graceful end point with at least a route for the user to contact the helpdesk - toggle the help beacon open  for example - as that will allow them to get in touch and will capture the page details where they hit the issue aiding the helpdesk staff to triage /resolve the issue.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/12462002/188118383-faa53fc4-67b7-4f87-845a-88d98a3234b9.png">

**Comment by gap736uk** [comment]
(ideally for 403 errors it would be good to either indicate the associated catalogue page for the user to apply for access or, if not available, a message indicating that they need to contact CEDA for access (we have default text we use for this in the catalogue when the access route isn't defined)

**Comment by spepler** [comment]
This is a dap error not a archive_bowser error.
